# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

variables:
- group: AWS-Credentials

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.x'
  displayName: 'Install Python'

- task: NodeTool@0
  inputs:
    versionSpec: 10.x

- script: npm install
  displayName: 'Npm Install'

- script: |
    npm run build
  displayName: 'Stencil Build'

- script: |
    npm run test
  displayName: 'Run Stencil Tests'

- script: |
    PATH="$PATH:$HOME/vsts/.local/bin"
    pip2 install awscli --upgrade
    aws configure set aws_access_key_id $(ACCESS_KEY_ID)
    aws configure set aws_secret_access_key $(SECRET_ACCESS_KEY)
    aws s3 sync ./www/ s3://eberhardtest
    aws s3 cp ./www/ s3://eberhardtest/ --recursive --exclude "*" --include "*.js" --content-type "application/javascript"
  displayName: 'aws install and sync'
